--산술연산자
SELECT ENAME , SAL, SAL *1.1 --급여 10%인상
FROM T_EMP ;

SELECT ENAME , SAL , COMM , SAL + COMM -- null 값과의 산술연산은 무조건 null
FROM T_EMP ;

--WHERE 조건절
SELECT * FROM T_EMP WHERE JOB = 'SALESMAN';

SELECT ENAME , SAL , DEPTNO 
FROM T_EMP 
WHERE DEPTNO = 10;

SELECT ENAME , SAL 
FROM T_EMP 
WHERE SAL > 2000;

SELECT ENAME , EMPNO , SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT';

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE BETWEEN 2 AND 3;4

SELECT NAME, GRADE FROM T_STUDENT WHERE GRADE = 2 OR GRADE =3;
SELECT NAME, GRADE FROM T_STUDENT WHERE GRADE IN(2,3);
SELECT NAME, GRADE FROM T_STUDENT WHERE GRADE >1 AND GRADE <4;
SELECT NAME, GRADE FROM T_STUDENT WHERE GRADE NOT IN(1,4);


SELECT NAME , PAY , POSITION
FROM T_PROFESSOR 
WHERE PAY > 300 AND POSITION = '정교수';

SELECT NAME , POSITION 
FROM T_PROFESSOR 
WHERE BONUS IS NULL;

SELECT NAME 
FROM T_PROFESSOR 
WHERE NAME LIKE '김%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%NE%';

SELECT ENAME FROM T_EMP WHERE ENAME LIKE '_A%';

SELECT ENAME FROM T_EMP WHERE ENAME LIKE '%L%' ORDER BY ENAME DESC;

SELECT ENAME, JOB , SAL 
FROM T_EMP 
ORDER BY JOB DESC, SAL ASC;

SELECT NAME, GRADE, HEIGHT 
FROM T_STUDENT 
ORDER BY GRADE ASC , HEIGHT DESC ;














