SELECT * FROM T_PROFESSOR;
SELECT COUNT(*), COUNT(HPAGE) FROM T_PROFESSOR; -- 그룹함수에서는 null값은 계산에서 제외
SELECT COUNT(bonus), SUM(bonus), avg(bonus) FROM T_PROFESSOR; --bonus를 받는 사람들만 나온다
SELECT MAX(HIREDATE), MIN(HIREDATE) FROM T_EMP;

--NULL허용컬럼의 그룸함수 적용시
--nvl, nvl2 사용해야 정확한 값 나옴
SELECT avg(bonus), avg(nvl(bonus,0))
FROM T_PROFESSOR;

--t_professor 테이블에서 ‘학과별’로 교수들의 평균 보너스를 출력

--SELECT절에서는 그룹함수와 그룹함수가 아닌거는 같이 사용못함
--SELECT DEPTNO, AVG(BONUS) 
--FROM T_PROFESSOR;

SELECT DEPTNO, ROUND(AVG(NVL(BONUS,0)), 1) 보너스평균 
FROM T_PROFESSOR
GROUP BY DEPTNO;

--#5101
SELECT DEPTNO, POSITION, AVG(PAY) "평균급여"
FROM T_PROFESSOR
GROUP BY DEPTNO, POSITION
ORDER BY DEPTNO ASC, POSITION ASC;

--부서별 평균급여를 출력하되, 평균급여가 450 보다 많은 부서만 출력
SELECT DEPTNO, AVG(PAY) "평균급여"
FROM T_PROFESSOR
GROUP BY DEPTNO
HAVING AVG(PAY) > 450;

--SELECT 쿼리문 순서 : 순서 중요!
/*
 * SELECT
 * FROM
 * WHERE
 * GROUP BY
 * HAVING
 * ORDER BY
 */

--#5102
SELECT MGR "매니저", COUNT(MGR) "직원수",
	SUM(SAL) "급여총액", AVG(SAL) "급여평균",
	AVG(NVL(COMM, 0)) 
FROM T_EMP
WHERE JOB <> 'PRESIDENT'
GROUP BY MGR
--HAVING MGR IS NOT NULL
;

--#5103
SELECT DEPTNO, COUNT(DEPTNO) "총인원",
	AVG(ROUND(SYSDATE-HIREDATE, 1)) "근속평균",
	AVG(PAY) "급여평균",
	AVG(NVL(BONUS, 0)) "보너스평균"
FROM T_PROFESSOR
WHERE POSITION = '정교수' OR POSITION = '조교수'
--WHERE POSITION LIKE '%교수'
GROUP BY DEPTNO
;

--#5104
SELECT DEPTNO1 "학과", COUNT(DEPTNO1) "학생수",
	MAX(WEIGHT)-MIN(WEIGHT) "몸무게차"
FROM T_STUDENT 
GROUP BY DEPTNO1
;

--#5105
SELECT DEPTNO1 "학과", COUNT(DEPTNO1) "학생수",
	MAX(WEIGHT)-MIN(WEIGHT) "몸무게차"
FROM T_STUDENT 
GROUP BY DEPTNO1
HAVING MAX(WEIGHT)-MIN(WEIGHT) >=30
;



